import { FeedProvider } from '@digital-www-pwa/feed-provider';
import './global.css';

export const metadata = {
  title: 'Welcome to digital-www-pwa',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <FeedProvider>{children}</FeedProvider>
      </body>
    </html>
  );
}
