import './global.css';

import { TopNavComponent } from '@digital-www-pwa/top-nav-component';

import { FeedProvider } from '@digital-www-pwa/feed-provider';

export const metadata = {
  title: 'Lakes of Fire 2025 Digital WWW',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-gray-100">
      <body className="h-full">
        <div className="min-h-full">
          <TopNavComponent />
          <FeedProvider>{children}</FeedProvider>
        </div>
      </body>
    </html>
  );
}
